services:
    - type: web
      name: mlops-app
      env: python
      plan: starter
      buildCommand: poetry install
      startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
      autoDeploy: false
