data:
    car_prices:
        raw:
            path: "data/raw/02_Used_Car_Prices.xlsx"
        processed:
            path: "data/processed/02_Used_Car_Prices.xlsx"
    house_prices:
        raw:
            path: "data/raw/01_Melbourne_Residential.csv"
        processed:
            path: "data/processed/01_Melbourne_Residential.csv"
    wheat_prices:
        raw:
            path: "data/raw/03_Wheat_Seeds.csv"
        processed:
            path: "data/processed/03_Wheat_Seeds.csv"

model:
    car_prices:
        path: "models/final_model"
    house_prices:
        path: "models/best_housing_model"
    wheat_prices:
        path: "models/wheat-pipeline"
